### PR TITLE
crime data modeling

### PR DESCRIPTION
**Pull request by gthrone25**
a first of hopefully many data modeling examples

### CODE REVIEW

**Comment by gthrone25** [comment]
@travisturner I'd love your thoughts/review on this 🙏  0 urgency

**Comment by gthrone25** [comment]
@kordless since you already read over this, do you mind approving or making any comments?

**Comment by kordless** [comment]
Oh yes.

**Comment by kordless** [comment]
LGT my bot

**Review by kordless — APPROVED** [review]
Love the way it's written! Ship it.

We can do a guide on loading this data maybe!

**Comment by gthrone25** [comment]
@kordless Ya we can iterate. I have all the code to load this up to it's fictional point. It can be my first github repo content for ya :). But in the future

**Pull request merged**
