### PR TITLE
deleted old datatypes page

### PR DESCRIPTION
**Pull request by ljsinclair**
one file this time.
Am getting the hang of it? ;)

### CODE REVIEW

**Review by gthrone25 — CHANGES_REQUESTED** [review]
@ljsinclair I realize seeing this it's important to have the featurebase datatype mapping somewhere in the new pages for string,stringset, id, and idset. Seems like it could be in additional information for each type? This information will help those in the community understand datatypes using SQL vs other methods (ingesters, http api, etc.) they have

**Comment by ljsinclair** [comment]
Perhaps instead of putting the data types under sql-preview, it could be a separate folder?

**Comment by gthrone25** [comment]
You just finished putting all of the datatypes under sql-preview, so let's keep them there for now. I think they make most sense there as they are specific to sql-preview and are needed by users when creating tables

**Comment by ljsinclair** [comment]
new branch to handle this as main has moved on and there's conflicts

**Comment by ljsinclair** [comment]
This is done, so closing.

**Pull request closed without merging**
