### PR TITLE
updates on ddl and constraints based on changes

### PR DESCRIPTION
**Pull request by gthrone25**
Changes based on the following:
shardwidth and keypartitions functionality removed
cachetype constraint removed
DDL examples updated based on the above
Syntax -> DDL Syntax based on confused user feedback

### CODE REVIEW

**Review by pokeeffe-molecula — APPROVED** [review]
yolo

**Comment by gthrone25** [comment]
@ljsinclair letting you merge so that you're aware of the change before it goes in

**Comment by ljsinclair** [comment]
Appreciated :) I'll get these across today :)

**Comment by gthrone25** [comment]
@ljsinclair I'm pushing these in

**Comment by ljsinclair** [comment]
Thanks Greg, will get them over to the new help today :)

**Pull request merged**
