### PR TITLE
Docs 73

### PR DESCRIPTION
**Pull request by ljsinclair**
Hi @gthrone25 

Here's the first draft on the cloud database rewrites and redesign.
There's a bunch of new pages contained in a new folder: /cloud-databases
Ideally the first 2 pages in nav would be manage databases and manage tables, however the date stamp naming escapes me at this point in the day. This is another of those problems that will be more easily solved with a new theme
This work will replace:
* https://docs.featurebase.com/cloud/cloud-data-modeling/data-types
* https://docs.featurebase.com/cloud/cloud-data-ingestion/tables
And also the database and table creation content in the multiple install/getting started guides.
NOTE: the files with "API" on the end, plus the data-types have **missing content** which will need to be filled in before this goes live. I've done the best I could with the information on-hand.
Now as discussed, there are a *lot* of changes in the branch, HOWEVER these are rolling updates on new files so there should be minimal conflicts. (said the blind man before walking off the cliff) :D

### CODE REVIEW

**Comment by gthrone25** [comment]
@ljsinclair 
1. This is awesome! The amount of progress is a big 💪 
2.  You're gonna be annoyed (but I did warn ya...). We have to  break this up into many smaller PRs. Why? I won't have all the answers to review these and need to round robin to people across the company. Additionally, this is too large to know what all is going on. Each PR should be clear in that x pages are being deleted in place of y new pages.  An example would be how you broke the database pages up. That should be one logical grouping to review and not with data type stuff, community stuff, index stuff, etc. Hoping we can sync today because tomorrow is my last day before I'm out for a week, but if you can break this up for tomorrow, I can assign things to be reviewed and merged in!

**Comment by ljsinclair** [comment]
Not annoyed at all. I suspected this might happen.
I'll sort this out now and let you know :)

**Comment by ljsinclair** [comment]
Hi @gthrone25 
As discussed, I've worked to clean up the content for this PR:
* API content has been removed and hyperlinks now direct to the API docs
* data-types content has been copied locally but deleted from the branch because the content needs to be reviewed (nothing hyperlinked to this content so this was the simplest option)
The site builds on the remote site.
I believe the links all work

**Comment by gthrone25** [comment]
@ljsinclair I took a look at database creation and the linking to api docs, which is looking good. I'm not able to do a thorough review of this stuff, so that will have to wait. Still assuming this will be broken down further when it comes to merging in? Or is this requiring 64 changes all together?

**Comment by ljsinclair** [comment]
Basically the changes are just what's in:
* /cloud-databases
* /cloud-tables
* /cloud-api
Plus changes to:
* /index.html - to add the FeatureBase description you suggested
* /cloud/fbc-part2-login - to direct users to the new cloud databases content
* /cloud-data-ingestion/streaming-https-endpoint/cloud-streaming-overview - added standardised before you begin links
New issues files were also added (which I totally forgot to mention earlier)
* /cloud-setup/issue-limit-reached
* /query-cloud-data/issue-network-error-on query

I'll create Jiras next week for working on:
* the data types doco - initial work is complete but it needs input from dev before pushing to prod
* the API doco - which now has its own folder **but** needs a total overhaul because API docs are in redocly

**Comment by ljsinclair** [comment]
## Update 2022-11-29
New PRs for these branches and content:
* cloud API
* cloud-databases
* cloud-tables
* new-index
Just going to go through and trace anything else that's changed in this PR before it can be closed without action

**Pull request closed without merging**
